default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)
  redirect_uri: 'http://127.0.0.1:6969/'
shinyapps:
  redirect_uri: 'https://ngoodkind.shinyapps.io/strava-recap/'
